comment: false

codecov:
  token: 972cfe9f-2f9b-4092-8241-2453c0475deb

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
